version: '3.7'

services:

  angular-app:
    container_name: 'angular-app-dev'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'